### ISSUE TITLE
Feature: Restructure Configuration for Manager and Agent Services

### ISSUE THREAD

**Issue by SammyOina** [ultravioletrs/cocos#209]
## Background
We currently have two configuration structures for our manager and agent services. Both services share the same gRPC server and client library code, but attested TLS should only be usable for the agent service.

### Client Config
```go
type Config struct {
	ClientCert   string        `env:"CLIENT_CERT"     envDefault:""`
	ClientKey    string        `env:"CLIENT_KEY"      envDefault:""`
	ServerCAFile string        `env:"SERVER_CA_CERTS" envDefault:""`
	URL          string        `env:"URL"             envDefault:"localhost:7001"`
	Timeout      time.Duration `env:"TIMEOUT"         envDefault:"60s"`
	AttestedTLS  bool          `env:"ATTESTED_TLS"    envDefault:"false"`
	Manifest     string        `env:"MANIFEST"        envDefault:""`
}
```

### Server Config
```go
type Config struct {
	Host         string `env:"HOST"               envDefault:""`
	Port         string `env:"PORT"               envDefault:""`
	CertFile     string `env:"SERVER_CERT"        envDefault:""`
	KeyFile      string `env:"SERVER_KEY"         envDefault:""`
	ServerCAFile string `env:"SERVER_CA_CERTS"    envDefault:""`
	ClientCAFile string `env:"CLIENT_CA_CERTS"    envDefault:""`
	AttestedTLS  bool   `env:"ATTESTED_TLS"       envDefault:"false"`
}
```

## Proposed Changes

1. Create a base configuration structure for common fields.
2. Create separate structures for manager-specific and agent-specific configurations.
3. Embed the base configuration in both manager and agent configurations.
4. Move TLS-related fields to the agent configuration only.

## Benefits
- Clear separation of concerns between manager and agent configurations.
- attested TLS-related fields are explicitly only available for the agent service.
- Shared fields are centralized in the BaseConfig, reducing duplication.
- Easier to maintain and extend in the future.

## Tasks
- [ ] Implement the new configuration structures
- [ ] Update the manager service to use ManagerConfig
- [ ] Update the agent service to use AgentConfig
- [ ] Adjust any code that relies on the old configuration structures
- [ ] Update documentation to reflect the new configuration structure
- [ ] Add tests to ensure proper functioning with the new configuration

### Indicate the importance of this feature to you.

Must-have

**Comment by dborovcanin** [comment]
@FilipCivljak What's the status with this one?
